# Generated by Django 4.1 on 2022-08-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateField(auto_created=True)),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=122)),
                ('body', models.CharField(max_length=122)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
